tutorial3-5/firstproject/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("poll/", include("poll.urls")),
    path("admin/", admin.site.urls),
    path('', views.index, name='index'),  # serve index.html at the root URL
]

tutorial3-5/poll/urls.py
from django.urls import path

from . import views

app_name= "poll"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/",views.detail,name="detail"),
    path("<int:question_id>/results/",views.results,name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),    
    
    ]

tutorial3-5/poll/models.py
from django.db import models
from django.utils import timezone
import datetime  # Ensure this is imported

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField("Date published")
    # is_answered = models.BooleanField("Is this question is answered", default=False)
    # is_correct = models.BooleanField("Is this question is correct", default=False)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()  # datetime.datetime
        one_day_ago = now - datetime.timedelta(days=1)
        future_days = now + datetime.timedelta(days=1)
        return self.pub_date >= one_day_ago and self.pub_date < now
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


    def __str__(self):
        return self.choice_text
    

tutorial3-5/firstproject/views.py
from django.shortcuts import render
from . import settings

def index(request):

    return render(request,"index.html")

tutorial3-5/poll/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from poll.models import Choice, Question
from django.utils import timezone
from django.db.models import F
# Create your views here.
from django.views import generic
from django.utils import timezone

def index(request):
    content = {"a":[1,2,34]}
    latest_question_list = Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list,"a" : content["a"]}
    return render(request,"poll/index.html",context)

# admin@gmail.com   123  admin


def detail(request, question_id):
    question = get_object_or_404(
        Question,
        pk=question_id,
        pub_date__lte=timezone.now()
    )
    return render(request, "poll/detail.html", context={"question": question})



def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    max_votes = 0
    top_choice = None

    for choice in question.choice_set.all():
        if choice.votes > max_votes:
            max_votes = choice.votes
            top_choice = choice

    return render(request, 'poll/result.html', {
        "question": question,
        "top_choice": top_choice,
        "max_votes": max_votes
    })


def vote(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "poll/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        selected_choice.refresh_from_db() 
        print(selected_choice.votes)

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("poll:results", args=(question.id,)))
    


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]
    



class DetailView(generic.DetailView):
    ...

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
    
def get_queryset(self):
    """
    Return the last five published questions (not including those set to be
    published in the future).
    """
    return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
        :5
    ]

tutorial3-5/poll/templates/poll/detail.html
<form action="{% url 'poll:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>
      <h1>{{ question.question_text }}</h1>
    </legend>
    {% if error_message %}
    <p>
      <strong>{{ error_message }}</strong>
    </p>

    {% endif %} {% for choice in question.choice_set.all %}
    <input
      type="radio"
      name="choice"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
    ><br />
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote" />
</form>

tutorial3-5/poll/templates/poll/index.html
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li>
    <a href="{% url 'poll:detail' question.id %}"
      >{{ question.question_text }}</a
    >
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

tutorial3-5/poll/templates/poll/result.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h3>{{ question }}</h3>
    <i>Choice :</i> {{ top_choice }} <br />
    <i>Maximum vote :</i>{{ max_votes }}
  </body>
</html>

tutorial3-5/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello this is index page</h1>
    <a href= {% url "poll:index" %} >poll app</a>
</body>
</html>